INSERT INTO AnimalType (name) VALUES
    ("Ave"),
    ("Reptil"),
    ("Mamífero"),
    ("Anfibio"),
    ("Otro");

INSERT INTO Species (common_name, scientific_name, animal_type_id) VALUES
("Tecolote bajeño", "Glaucidium brasilianum", 1),
("Lechuza de campanario", "Tyto alba", 1),
("Carpintero Cheje Yucateco", "Melanerpes aurifrons ssp. Dubius", 1),
("Colibri canela", "Amazilia rutila", 1),
("Tapacaminos yucateco", "Nyctiphrynus yucatanicus", 1),
("Momoto cejiazul", "Eumomota superciliosa", 1),
("Momoto corona negra", "Momotus lessonii", 1),
("Pájaro estaca norteño", "Nyctibius jamaicensis", 1),
("Luis bienteveo", "Pitangus sulphuratus", 1),
("Aguililla caminera", "Rupornis magnirostris", 1),
("Cenzontle tropical", "Mimus gilvus", 1),
("Zopilote común", "Coragyps atratus", 1),
("Zanate Mayor", "Quiscalus mexicanus", 1),
("Tordo de ojos rojos", "Molothrus aeneus", 1),
("Garcita Verde", "Butorides virescens", 1),
("Ninfa", "Nymphicus hollandicus", 1),
("Loro australiano", "Melopsittacus undulatus", 1),
("Chipe encapuchado", "Setophaga citrina", 1),
("Paloma alas blancas", "Zenaida asiática", 1),
("Mirlo café", "Turdus grayi", 1),
("Pato doméstico", "Anas platyrhynchos domesticus", 1),
("Calandria dorso negro mayor", "Icterus gularis", 1),
("Boa", "Boa imperator", 2),
("Ratonera Olivo", "Senticolis triaspis", 2),
("Culebra lisa", "Coniophanes meridanus", 2),
("Iguana rayada", "Ctenosaura similis", 2),
("Culebra lagartijera", "Mastigodryas melanolomus", 2),
("Culebra rayada", "Coniophanes schmidti", 2),
("Culebra ojos de gato", "Leptodeira frenata", 2),
("Culebra ciega afroasiática", "Indotyphlops braminus", 2),
("Culebra ciempiés yucateca", "Tantillita canula", 2),
("Culebra ciega yucateca", "Amerotyphlops microstomus", 2),
("Bejuquilla verde", "Oxybelis fulgidus", 2),
("Coralillo", "Micrurus apiatus", 2),
("Serpiente de Cascabel", "Crotalus tzabcan", 2),
("Serpiente Corredora de Petatillos", "Drymobius margaritiferus", 2),
("Tortuga Mojina de monte", "Rhinoclemmys areolata", 2),
("Tortuga de caja amarilla yucateca", "Terrapene yucatana", 2),
("Tortuga de pantano yucateca", "Kinosternon creaseri", 2),
("Tortuga de labios blancos mexicana", "Kinosternon leucostomun", 2),
("Pochitoque o tortuga de pecho quebrado", "Kinosternon scorpioides", 2),
("Tortuga Pavo Real o jicotea", "Trachemys venusta", 2),
("Tortuga Japonesa o de orejas naranjas", "Trachemys scripta elegans", 2),
("Tortuga vampiro", "Claudius angustatus", 2),
("Tortuga del desierto", "Gopherus berlandieri", 2),
("Culebra perico mexicana", "Leptophis mexicanus", 2),
("Iguana de cola espinosa", "Cachryx defensor", 2),
("Gecko de bandas yucateco", "Coleonix elegans", 2),
("Zarigueya", "Didelphis virginiana", 3),
("Zorrillo Manchado", "Spilogale angustifrons", 3),
("Coatí", "Nasua narica", 3),
("Oso Hormiguero", "Tamandua mexicana", 3),
("Murcielago Mastin Común", "Molossus molossus", 3),
("Murciélago Amarillo Yucateco", "Rhogeessa aeneus", 3),
("Murcielago Frugívoro ", "Artibeus jamaicensis", 3),
("Zorro gris", "Urocyon cinereoargenteus", 3),
("Ardilla Yucateca", "Sciurus yucatanensis", 3),
("Sapo costero", "Incilius valliceps", 4),
("Sapo gigante", "Rhinella horribilis", 4),
("Rana arborícola Vermiculada", "Trachycephalus vermiculatus", 4),
("Rana leopardo", "Lithobathes brownorum", 4),
("Rana arborícola mexicana", "Smilisca baudiniii", 4),
("Rana pico de pato", "Triprion petasatus", 4),
("Ranita hojarasca", "Leptodactylus melanonotus", 4),
("Ranita de labios blancos", "Leptodactylus labialis", 4),
("Abeja europea", "Apis mellifera", 5),
("Avispa guitarrilla", "Polistes instabilis", 5),
("Chinche gigante de agua", "Lethocerus sp", 5),
("Chinche besucona", "Triatoma dimidiata", 5),
("Tarántula de trasero rojo", "Tliltocatl epicureanum", 5);